AWSTemplateFormatVersion: '2010-09-09'
Description: Process Lambda with S3, DynamoDB, and API Gateway

Parameters:
  BucketName:
    Type: String
  TableName:
    Type: String

Resources:
  ProcessFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ProcessLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InlineExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - textract:AnalyzeExpense
                  - dynamodb:PutItem
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ProcessFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ProcessExpenseFunction
      Handler: handler.process
      Role: !GetAtt ProcessFunctionRole.Arn
      Runtime: python3.11
      Timeout: 60
      MemorySize: 256
      Code:
        S3Bucket: !Ref BucketName
        S3Key: lambda/process_lambda.zip
      Environment:
        Variables:
          BUCKET: !Ref BucketName
          TABLE: !Ref TableName

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ProcessApi

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: process
      RestApiId: !Ref ApiGateway

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessFunction.Arn}/invocations

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessFunction
      Principal: apigateway.amazonaws.com
